import {
  Book,
  BriefcaseBusiness,
  ChevronDownIcon,
  ChevronUp,
  CirclePlay,
  Facebook,
  Fingerprint,
  Instagram,
  Linkedin,
  Menu,
  MessageCircle,
  MoveRight,
  Phone,
  Search,
  Shield,
  Star,
  Twitter,
  Users,
  X,
  Youtube,
} from "lucide-react";

export const ICONS = {
  BARS: Menu,
  CLOSE: X,
  ARROW_DOWN: ChevronDownIcon,
  ARROW_UP: ChevronUp,
  MOVE_RIGHT: MoveRight,
  PHONE: Phone,
  FINGERPRINT: Fingerprint,
  CIRCLE_PLAY: CirclePlay,
  SEARCH: Search,
  STAR: Star,
  SHIELD: Shield,
  USERS: Users,
  BRIEFCASE: BriefcaseBusiness,
  BOOK: Book,
  MESSAGECIRCLE: MessageCircle,

  //Social Icons
  FACEBOOK: Facebook,
  LINKEDIN: Linkedin,
  TWITTER: Twitter,
  INSTAGRAM: Instagram,
  YOUTUBE: Youtube,
};
